---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 80, host: 8080}]
    - ["private_network", {ip: "192.168.33.34"}]  
provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  #- name: ubuntu-16.04
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[webserver-cookbook::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes: